package com.basic.domain;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.basic.domain.base.BaseChargeflow;
import com.basic.query.ChargeflowQueryObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Chargeflow extends BaseChargeflow<Chargeflow> {
	public static final Chargeflow dao = new Chargeflow().dao();
	public Page<Chargeflow> paginate(ChargeflowQueryObject qo) {
		SqlPara sqlPara = getSqlParaFromTemplate(Kv.by("qo", qo));
		return dao.paginate(qo.getCurrentPage(), qo.getPageSize(), sqlPara);
	}
}
