package com.basic.domain;

import com.jfinal.kit.Kv;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.SqlPara;
import com.basic.domain.base.BaseManager;
import com.basic.query.ManagerQueryObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manager extends BaseManager<Manager> {
	public static final Manager dao = new Manager().dao();
	public Page<Manager> paginate(ManagerQueryObject qo) {
		SqlPara sqlPara = getSqlParaFromTemplate(Kv.by("qo", qo));
		return dao.paginate(qo.getCurrentPage(), qo.getPageSize(), sqlPara);
	}
}
