package com.basic.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMeat<T extends BaseMeat> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Long id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public T setUsetime(java.lang.Integer usetime) {
		set("usetime", usetime);
		return (T)this;
	}
	
	public java.lang.Integer getUsetime() {
		return getInt("usetime");
	}

	public T setPrice(java.lang.Float price) {
		set("price", price);
		return (T)this;
	}
	
	public java.lang.Float getPrice() {
		return getFloat("price");
	}

	public T setState(java.lang.Integer state) {
		set("state", state);
		return (T)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
