package com.basic.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSystemaccount<T extends BaseSystemaccount> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Long id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public T setInput(java.lang.Float input) {
		set("input", input);
		return (T)this;
	}
	
	public java.lang.Float getInput() {
		return getFloat("input");
	}

	public T setOutput(java.lang.Float output) {
		set("output", output);
		return (T)this;
	}
	
	public java.lang.Float getOutput() {
		return getFloat("output");
	}

	public T setEnabledAccount(java.lang.Integer enabledAccount) {
		set("enabledAccount", enabledAccount);
		return (T)this;
	}
	
	public java.lang.Integer getEnabledAccount() {
		return getInt("enabledAccount");
	}

	public T setAccountNum(java.lang.Integer accountNum) {
		set("accountNum", accountNum);
		return (T)this;
	}
	
	public java.lang.Integer getAccountNum() {
		return getInt("accountNum");
	}

}
