package com.basic.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseManager<T extends BaseManager> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Long id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public T setRealname(java.lang.String realname) {
		set("realname", realname);
		return (T)this;
	}
	
	public java.lang.String getRealname() {
		return getStr("realname");
	}

}
