package com.basic.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseChargeflow<T extends BaseChargeflow> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Long id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public T setChargeTime(java.util.Date chargeTime) {
		set("chargeTime", chargeTime);
		return (T)this;
	}
	
	public java.util.Date getChargeTime() {
		return get("chargeTime");
	}

	public T setDeadLineTime(java.util.Date deadLineTime) {
		set("deadLineTime", deadLineTime);
		return (T)this;
	}
	
	public java.util.Date getDeadLineTime() {
		return get("deadLineTime");
	}

	public T setAccountId(java.lang.Long accountId) {
		set("account_id", accountId);
		return (T)this;
	}
	
	public java.lang.Long getAccountId() {
		return getLong("account_id");
	}

	public T setChargerId(java.lang.Long chargerId) {
		set("charger_id", chargerId);
		return (T)this;
	}
	
	public java.lang.Long getChargerId() {
		return getLong("charger_id");
	}

	public T setChargeAmount(java.lang.Float chargeAmount) {
		set("chargeAmount", chargeAmount);
		return (T)this;
	}
	
	public java.lang.Float getChargeAmount() {
		return getFloat("chargeAmount");
	}

}
