package com.basic.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBorrowflow<T extends BaseBorrowflow> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Long id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public T setBorrowTime(java.util.Date borrowTime) {
		set("borrowTime", borrowTime);
		return (T)this;
	}
	
	public java.util.Date getBorrowTime() {
		return get("borrowTime");
	}

	public T setBorrowmenuId(java.lang.Long borrowmenuId) {
		set("borrowMenu_id", borrowmenuId);
		return (T)this;
	}
	
	public java.lang.Long getBorrowmenuId() {
		return getLong("borrowMenu_id");
	}

	public T setAccountId(java.lang.Long accountId) {
		set("account_id", accountId);
		return (T)this;
	}
	
	public java.lang.Long getAccountId() {
		return getLong("account_id");
	}

	public T setBorrowerId(java.lang.Long borrowerId) {
		set("borrower_id", borrowerId);
		return (T)this;
	}
	
	public java.lang.Long getBorrowerId() {
		return getLong("borrower_id");
	}

}
