package com.basic.domain.base;

import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccount<T extends BaseAccount> extends SuperModel<T> implements IBean {

	public T setId(java.lang.Long id) {
		set("id", id);
		return (T)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public T setAccountname(java.lang.String accountname) {
		set("accountname", accountname);
		return (T)this;
	}
	
	public java.lang.String getAccountname() {
		return getStr("accountname");
	}

	public T setPassword(java.lang.String password) {
		set("password", password);
		return (T)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public T setState(java.lang.Integer state) {
		set("state", state);
		return (T)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public T setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (T)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public T setPossesserId(java.lang.Long possesserId) {
		set("possesser_id", possesserId);
		return (T)this;
	}
	
	public java.lang.Long getPossesserId() {
		return getLong("possesser_id");
	}

	public T setDeadLineTime(java.util.Date deadLineTime) {
		set("deadLineTime", deadLineTime);
		return (T)this;
	}
	
	public java.util.Date getDeadLineTime() {
		return get("deadLineTime");
	}

	public T setOuttime(java.util.Date outtime) {
		set("outtime", outtime);
		return (T)this;
	}
	
	public java.util.Date getOuttime() {
		return get("outtime");
	}

	public T setInput(java.lang.Float input) {
		set("input", input);
		return (T)this;
	}
	
	public java.lang.Float getInput() {
		return getFloat("input");
	}

	public T setOutput(java.lang.Float output) {
		set("output", output);
		return (T)this;
	}
	
	public java.lang.Float getOutput() {
		return getFloat("output");
	}

}
